### ISSUE TITLE
`AttachedState` is missing on xenial branch

### ISSUE THREAD

**Issue by z3ntu** [ubports/unity-api#22]
qtmir xenial branch uses `AttachedState` (https://github.com/ubports/qtmir/commit/6c2aa53cfcb2865481ceb5df7456672d6c8010f9) but https://github.com/ubports/unity-api/commit/0658a40ba4ef5bd7221642fc051983a53026ca35 is only in the `xenial_-_mir16` branch breaking compilation.

**Comment by z3ntu** [comment]
I just found https://github.com/ubports/qtmir/commit/06c1efd2151b820f01c95f387bd79a305adc3182 in `xenial_-_edge_-_wayland`

**Comment by UniversalSuperBox** [comment]
unity-api is moving to GitLab and has been renamed to lomiri-api. It's possible that the issue you report has been fixed in the main branch there. https://gitlab.com/ubports/core/lomiri-api
